server:
  #  port: 9092
  servlet:
    context-path: /
spring:
  #  redis:
  #    host: 1.1.1.1
  #    port: 6379
  #    password:
  #  datasource:
  #    dynamic:
  #      primary: db0
  #      druid: #全局druid
  #        initial-size: 0
  #        max-active: 100
  #        min-idle: 10
  #        max-wait: 60000
  #        min-evictable-idle-time-millis: 300000
  #        time-between-eviction-runs-millis: 60000
  #        validation-query: select 1 from dual
  #        test-on-borrow: false
  #        test-on-return: false
  #        test-while-idle: true
  #        pool-prepared-statements: true
  #        filters: stat,wall
  #        # max-open-prepared-statements: 100
  #        # max-pool-prepared-statement-per-connection-size 替代 max-open-prepared-statements
  #        max-pool-prepared-statement-per-connection-size: 100
  #        share-prepared-statements: true
  #        connection-properties: druid.stat.mergeSql=true
  #        use-global-data-source-stat: false
  #        time-between-log-stats-millis: 86400000
  #        proxy-filters:
  #          - druidWallFilter
  #      datasource:
  #        db0:
  #          url: jdbc:mysql://host1/db0?autoReconnectForPools=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  #          username: root
  #          password: 123
  #          driver-class-name: com.mysql.cj.jdbc.Driver
  #        db1:
  #          url: jdbc:mysql://host2/db0?autoReconnectForPools=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  #            username: root
  #            password: 123
  #            driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: Freeeeeedom
  aop:
    proxy-target-class: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  mapper-locations: classpath:mapping/**/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    local-cache-scope: statement