spring:
  profiles:
    active: dev
#  validationQuery参数一览
#  Oracle	select 1 from dual
#  MySQL	select 1
#  Microsoft SQL Server	select 1
#  DB2	select 1 from sysibm.sysdummy1
#  SQLite	select 1
#  HSQLDB	select 1 from INFORMATION_SCHEMA.SYSTEM_USERS
#  postgresql	select version()
#  ingres	select 1
#  Apache Derby	select 1
#  H2	select 1
#  Informix	select count(*) from systables